name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile pysync/__main__.py --name pysync

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pysync-${{ matrix.runs-on }}
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup | Force release branch to be at workflow SHA
        run: |
          git reset --hard ${{ github.sha }}

      - name: Setup | Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Setup | Install dependencies
        run: |
          pip install python-semantic-release
          semantic-release --version

      - uses: actions/download-artifact@v4
        with:
          path: downloaded
      - name: Display structure of downloaded files
        run: ls -lR downloaded

      - name: Setup | Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: pysync-ubuntu-latest
      - name: Display structure of downloaded files
        run: ls -lR

      - name: Setup | Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: pysync-macos-latest
      - name: Display structure of downloaded files
        run: ls -lR

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      - name: Publish | Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        if: steps.release.outputs.released == 'true'

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.21.0
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
