name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile pysync/__main__.py --name pysync

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pysync-${{ matrix.runs-on }}
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup | Checkout Repository on Release Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup | Force release branch to be at workflow SHA
        run: |
          git reset --hard ${{ github.sha }}

      - name: Setup | Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Setup | Install dependencies
        run: pip install python-semantic-release

      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Show downloaded files
        run: ls -lR

      - name: Action | Semantic Version Release
        run: |
          printenv
          git checkout ${{ github.ref_name }}
          semantic-release --version
          semantic-release --strict version  # Create and publish a new release
