name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile pysync/__main__.py --name pysync

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: pysync-linux
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile pysync/__main__.py --name pysync

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: pysync-macos
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - uses: actions/checkout@v4
        with:
          path: downloaded
      - name: Display structure of downloaded files
        run: ls -R downloaded

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: pysync-linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: pysync-macos

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "pysync ${{ github.ref }}"
          draft: false
          prerelease: false
          body: "Automatically generated release for tag ${{ github.ref }}."

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pysync-linux/pysync
          asset_name: pysync-linux
          asset_content_type: application/octet-stream

      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pysync-macos/pysync
          asset_name: pysync-macos
          asset_content_type: application/octet-stream
